### PR TITLE
Add material snackbar theme

### LINKED ISSUE #82: Material theme for snackbar
Material snack bar details can be found here: https://material.io/develop/web/components/snackbars/

This can be implemented using composition and has already been done elsewhere.

### LINKED ISSUE #1063: Material theme for snackbar
Material snack bar details can be found here: https://material.io/develop/web/components/snackbars/

This can be implemented using composition and has already been done elsewhere.

### PR DESCRIPTION
**Pull request by nicknisi**
**Type:** feature

The following has been addressed in the PR:

* [x] There is a related issue
* [ ] All code has been formatted with [`prettier`](https://prettier.io/) as per the [readme code style guidelines](./../#code-style)
* [ ] Unit or Functional tests are included in the PR

**Description:**

This adds a Material snackbar composed of the theme from @material/snackbar.

image

Resolves #82

### CODE REVIEW

**Comment by nicknisi** [comment]
@tomdye Do you have any thoughts on how the success and error types should work for the snackbar in the material theme? Here are some ideas:
Napkin 11-23-19, 5 32 51 PM

**Comment by tomdye** [comment]
Looking at the material guidelines @nicknisi i think that it's just the action buttons that change colour

**Comment by nicknisi** [comment]
@tomdye ok, if that's the case, the `type` property won't really have an effect on a material snackbar because the rendering of the actions is completely handled by the `actionsRenderer` property.

**Comment by tomdye** [comment]
I'd have imagined that it would apply a class to the wrapper around the action buttons?

**Pull request merged**
